### ISSUE TITLE
Scripts are scattered.

### ISSUE THREAD

**Issue by DailyDreaming** [HumanCellAtlas/data-store#2025] opened 2019-04-08 15:41 UTC
It'd be nice to have one python file with a help menu for all of the separate scripts we have.

**Comment by kozbo** [comment] 2019-04-15 18:43
Devops task

**Comment by DailyDreaming** [comment] 2019-05-08 00:27
Looks like https://github.com/HumanCellAtlas/data-store/pull/2111 addresses this.

**Comment by xbrianh** [comment] 2019-07-29 22:53
Duplicate of #1613

**Closed by xbrianh** 2019-07-29 22:53 UTC
Labels: DevOps, LOW
