### ISSUE TITLE
Optionally provide a cloud native URL as output from GET /files/{uuid}

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2045] opened 2019-04-15 17:24 UTC
Some consumers of HCA file data require a cloud native (e.g. `gs://` or `s3://`) URL instead of a presigned URLs. One such consumer is the Broad's Terra (formerly FireCloud) system, which does not support presigned URLs but instead requires cloud native URLs for cloud data access.
This request is motivated by the current HCA Browser handoff to Terra development effort.

A proposed design is as follows:
- Enhance the DSS `GET /files/{uuid}` with an optional `directurl` query parameter, with the values `true` and `false` (default). This is consistent with the `GET /bundles/{uuid}` `directurls` query parameter.
- When `directurl=true`, in the final response from the `GET /files/{uuid}` operation (the response with HTTP code 302), returns the cloud native URL to the file in the checkout bucket in the `Location` header, instead of the presigned URL, for that same file/object.

@hannes-ucsc and I collaborated on this proposal, and consider it consistent with the definition of the HTTP 302 response in [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.4.3).

We are open to alternate designs, yet this seems simple and consistent.

It is understood that the with only the changes above, the cloud native URL path would be the "blob key" path (composed of a series of checksums) rather than the more user-meaningful cloud native paths produced by `GET /bundles/{uuid}`. This is "okay" for the purposes of the HCA Data Browser handoff to Terra, yet it _may_ be worth considering support for user meaningful names for file checkout as well (perhaps based on file UUID + version?), mostly for other use cases. This should be addressed in a separate issue(/PR), as it is a bigger "can of worms" and much lower priority.

Future Note:
This behavior is generally/broadly useful when HCA has only open access data and the checkout buckets have public access and #2055 is available. When HCA supports controlled access data, and the checkout buckets do not have public access, a means of providing credentials to use with the cloud native URL will also be needed.

Done When:
The DSS API provides cloud native URLs that are requested with per-file (not per bundle) granularity.

**Comment by mikebaumann** [comment] 2019-04-23 16:22
@kislyuk, are you fine with this change as currently described above?
The need for this was discussed at the Blue Box Architecture meeting on 4/8/19 (https://docs.google.com/document/d/1qqr8z-5OaFZX3uhGc10hnsrKwNuOb0vvzg88dbRK8Bc/edit#heading=h.5iphltimkd7).
As I recall, you were out of the office at the time, yet @mweiden attended and expressed support for providing cloud native URLs and enabling public access to the DSS managed checkout buckets, in support of workflow execution.

**Comment by kislyuk** [comment] 2019-04-26 21:18
@mikebaumann the general idea here is good and in line with DSS design. There are a couple of clarifications that we can make.

1. As part of this work, the `directurls`/`directurl` parameter should be better documented. The docstring for it in the swagger API definition should contain something like "When set to `true`, the response will contain API-specific URLs that are tied to the specified replica, for example `gs://bucket/object` or `s3://bucket/object`".

1. In your description, you say:

    > It is understood that the with only the changes above, the cloud native URL path would be the "blob key" path (composed of a series of checksums) rather than the more user-meaningful cloud native paths produced by GET /bundles/{uuid}. This is "okay" for the purposes of the HCA Data Browser handoff to Terra, yet it may be worth considering support for user meaningful names for file checkout as well (perhaps based on file UUID + version?), mostly for other use cases. This should be addressed in a separate issue(/PR), as it is a bigger "can of worms" and much lower priority.

    Support for meaningful names is already implemented by the checkout service - but only when checking out entire bundles. One of the reasons the checkout service was designed was to allow DSS to dispense object store-specific URLs that represent the filename in the last path component of the object name. For individual files, this is not available as their name is actually tied to the bundle metadata. Instead, a minimally disruptive change would be to *specify the `Content-Disposition` object metadata/header value* on the files in the checkout bucket to match the filename. This would still require the caller to provide a bundle ID that they're requesting the file in, or DSS to disambiguate or guess the bundle ID to get the filename.

1. > This behavior is generally/broadly useful when HCA has only open access data and the checkout buckets have public access and #2055 is available. When HCA supports controlled access data, and the checkout buckets do not have public access, a means of providing credentials to use with the cloud native URL will also be needed.

   DSS probably should not provide unauthenticated access to data in the managed checkout bucket. Providing unauthenticated access may be OK as a crutch in the short term, but it should be eliminated as soon as reasonable, because it will be a pain down the road if applications come to depend on it.
    - For S3, the credentials needed to access the file are already provided as components of the pre-signed URL. Accessing the file via an app that only understands `s3://` URLs would involve taking the AWS access key ID, key, and token from the pre-signed URL, and passing them to that app. (With `directurl=true`, DSS could provide these credentials as extra headers or in the JSON response body in the 302 redirect.)
    - For GS, there is no implemented option to provide cloud native access credentials, but a good short term solution would be to maintain a whitelist of trusted service account identities allowed to access the checkout bucket. A longer term option would be to implement [GS ACL](https://cloud.google.com/storage/docs/access-control/lists) writing and updating on the objects. Then the client who wants direct (cloud native) access on GS would specify the principal name to grant access to (or DSS could read that value from the auth token authenticating the API request to DSS), and DSS would write that principal's name into the ACL for the object if it's not there already.

**Closed** 2019-05-17 18:35 UTC
Labels: ENH, Story, api, orange
