### ISSUE TITLE
Support simple reindexing

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#226] opened 2017-07-14 17:11 UTC
It would be helpful to (re-)generate index entries for bundles already in a bucket, rather than uploading the bundles again to trigger indexing. This is intended primarily for development use cases at this point. Full system reindexing support would come later.

**Comment by hannes-ucsc** [comment] 2017-12-18 21:14
Dupe of #696 and #670.

**Closed** 2017-12-18 21:13 UTC
Labels: indexing/querying, ready
