### ISSUE TITLE
Design Specifications Stable

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#525] opened 2017-10-10 18:05 UTC
Design specifications shall be sufficiently documented to support integration efforts. @kislyuk and @kozbo we need to list all the design specification that need to ready updated in this issues.

### Design Specification to Update
- [ ] Logging  spec 
- [ ] Indexing spec

**Comment by kozbo** [comment] 2018-05-02 17:56
Closing as a duplicate of #522

**Closed by kozbo** 2018-05-02 17:56 UTC
Labels: Q2
