### ISSUE TITLE
Broken bundles in `staging` (or failed checkout)

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/data-store#1645] opened 2018-10-16 22:51 UTC
Azul [got](https://github.com/DataBiosphere/azul/issues/412#issuecomment-430342647) "too many retries" for `GET /files/UUID` for one of the files in bundles listed below. I suppose either the checkout failed or the bundle wasn't properly synced from GCP to AWS. If it was the latter, could you delete those bundles? Otherwise they would show up in our error fail queue on every reindexing forcing us to investigate the error every time.

```
'bundle_uuid': '4d939743-d276-4c78-a392-b2ead842c149', 'bundle_version': '2018-10-09T065905.634949Z'
'bundle_uuid': '67b859c2-ab56-457c-9da0-3445c150ce53', 'bundle_version': '2018-10-08T163821.235037Z'
'bundle_uuid': '9ded9d19-d690-4928-8d1b-df0f0bb16b2e', 'bundle_version': '2018-09-17T161449.293928Z'
'bundle_uuid': 'ecf22670-b79c-42c4-9679-07f6b836e940', 'bundle_version': '2018-10-04T031303.814854Z'
```

**Comment by Bento007** [comment] 2018-10-19 22:40
this will be resolved with the deletion script in the near future

**Comment by xbrianh** [comment] 2018-10-22 16:36
This appears to have been resolved. Root cause may have been failed sync.

**Closed by xbrianh** 2018-10-22 16:36 UTC
