### ISSUE TITLE
Query registration

### ISSUE THREAD

**Issue by kislyuk** [HumanCellAtlas/data-store#199] opened 2017-07-06 18:32 UTC

**Comment by briandoconnor** [comment] 2017-07-17 18:13
Michael, you should talked to Dave S. at the Broad about a use case he asked about.  Specifically, generating events from a query and not storing the query... kinda different but related to this.

**Comment by kozbo** [comment] 2017-07-24 18:16
duplicate of #248

**Closed** 2017-07-24 18:15 UTC
Labels: indexing/querying
