### ISSUE TITLE
 dcp-infra->prod gitlab access control

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1669] opened 2018-10-25 18:58 UTC
## User story
* As a operator
* I want to limit who has access to the production gitlab instance
* to control who can deploy and modify the production deployment

## Definition of done
access to the deployment server (gitlab/allspark) is controlled using a whitelist list of user with Terraform.

**Comment by kozbo** [comment] 2018-11-13 21:42
duplicate of allspark#56

**Closed** 2019-01-07 18:56 UTC
