### ISSUE TITLE
Understand and plan for ES schema/mapping evolution

### ISSUE THREAD

**Issue by mikebaumann** [HumanCellAtlas/data-store#289] opened 2017-07-28 12:08 UTC
ES mappings/schema have both capabilities and limitations for handling changes to the indexed data. These need to be understood to determine if they will meet our reasonably anticipated requirements. If they do, a plan will be needed for to use them.

**Comment by Bento007** [comment] 2017-10-10 23:51
is this a duplicate of #530?

**Comment by kozbo** [comment] 2017-10-23 17:22
First story of this Epic is #530

**Closed** 2017-11-27 20:04 UTC
Labels: Backlog, Epic, indexing/querying, Q4
