### ISSUE TITLE
speed up collection listing 

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#2007] opened 2019-04-01 20:46 UTC
## User story
* As a CLI user
* I want to iterate collections quickly
* so that listing large collections don't timeout

## Definition of done
Build an index of collections
should support finding if a collection contains a file or bundle (deletion support)

**Comment by DailyDreaming** [comment] 2019-04-15 20:25
This is a duplicate of the 2 tickets (data-store #2014) and (dcp-cli #291).

**Closed by DailyDreaming** 2019-04-15 20:25 UTC
Labels: collections
