### ISSUE TITLE
File Sync Failure

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/data-store#2298] opened 2019-07-29 21:50 UTC
Sync Failure alert due to missing UUID when trying to sync a file.

```: DSSException
Traceback (most recent call last):
File "/var/task/domovoi/app.py", line 223, in __call__
result = handler(event, context)
File "/var/task/app.py", line 327, in check_deps
if dependencies_exist(source_replica, dest_replica, event["source_key"]):
File "/var/task/domovoilib/dss/events/handlers/sync.py", line 249, in dependencies_exist
blobstore_handle=source_handle)
File "/var/task/domovoilib/dss/api/collections.py", line 213, in get_json_metadata
"Could not find file for UUID
{}
".format(uuid))
dss.error.DSSException
```

Found at 
 https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/dss-sync-sfn-dev;stream=2019/07/29/%5B$LATEST%5D208d306adb414c00b37cae3cd187449c;start=2019-07-28T20:39:45Z 

at time `20:37:05`

**Comment by DailyDreaming** [comment] 2019-08-24 01:44
This is not a `collections` error, not sure how that association was made.  The log just prior:
```
Domovoi - INFO - Domovoi dispatch of event {'source_replica': 'aws', 'dest_replica': 'gcp', 'source_key': 'files/2ab9e379-b9ca-4015-93a0-9d0d0b89df76.2019-07-29T203703.086334Z', 'source_obj_metadata': {'key': 'files/2ab9e379-b9ca-4015-93a0-9d0d0b89df76.2019-07-29T203703.086334Z', 'size': 19, 'eTag': 'a5890ace30a3e84d9118196c161aeec2', 'sequencer': '005D3F58EF1BF837BE'}, 'sleep': False, 'do_oneshot_copy': False, 'do_multipart_copy': False, 'done': False}
```
I've edited the original issue accordingly.  That said, this is a sync failure on `dev`, and occurred during the collections scale test that caused so many problems.  If not caused directly by the stress from that test, it might have been caused by us putting the dss into `read-only` mode that Monday morning (which was around that time if I remember correctly).

Closing this.  If a sync failure occurs again, a new ticket should be opened for that failure.

**Closed by DailyDreaming** 2019-08-24 01:44 UTC
Labels: BUG
