### ISSUE TITLE
Visitation Tests failed during integration

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1391] opened 2018-07-03 21:19 UTC
https://travis-ci.com/HumanCellAtlas/data-store/builds/78026686

```

======================================================================
ERROR: test_index_verification (__main__.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_visitation.py", line 297, in test_index_verification
    self._test('index', '--replica=aws', '--prefix=42', 'verify')
  File "tests/test_visitation.py", line 306, in _test
    output = self._get_execution_output(arn)
  File "/home/travis/build/HumanCellAtlas/data-store/tests/__init__.py", line 83, in call
    return func(*args, **kwargs)
  File "tests/test_visitation.py", line 315, in _get_execution_output
    require(status in ('SUCCEEDED', 'RUNNING'), f'Unexpected execution status: {status}')
  File "/home/travis/build/HumanCellAtlas/data-store/dss/util/__init__.py", line 91, in require
    reject(not condition, *args, exception=exception)
  File "/home/travis/build/HumanCellAtlas/data-store/dss/util/__init__.py", line 106, in reject
    raise exception(*args)
dss.util.RequirementError: Unexpected execution status: FAILED
======================================================================
ERROR: test_storage_verification_blobs (__main__.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_visitation.py", line 294, in test_storage_verification_blobs
    self._test('storage', '--replica=aws', '--replica=gcp', '--prefix=423', 'verify', '--folder=blobs')
  File "tests/test_visitation.py", line 306, in _test
    output = self._get_execution_output(arn)
  File "/home/travis/build/HumanCellAtlas/data-store/tests/__init__.py", line 83, in call
    return func(*args, **kwargs)
  File "tests/test_visitation.py", line 315, in _get_execution_output
    require(status in ('SUCCEEDED', 'RUNNING'), f'Unexpected execution status: {status}')
  File "/home/travis/build/HumanCellAtlas/data-store/dss/util/__init__.py", line 91, in require
    reject(not condition, *args, exception=exception)
  File "/home/travis/build/HumanCellAtlas/data-store/dss/util/__init__.py", line 106, in reject
    raise exception(*args)
dss.util.RequirementError: Unexpected execution status: FAILED
======================================================================
ERROR: test_storage_verification_bundles (__main__.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_visitation.py", line 291, in test_storage_verification_bundles
    self._test('storage', '--replica=aws', '--replica=gcp', '--prefix=423', 'verify', '--folder=bundles', '--quick')
  File "tests/test_visitation.py", line 306, in _test
    output = self._get_execution_output(arn)
  File "/home/travis/build/HumanCellAtlas/data-store/tests/__init__.py", line 83, in call
    return func(*args, **kwargs)
  File "tests/test_visitation.py", line 315, in _get_execution_output
    require(status in ('SUCCEEDED', 'RUNNING'), f'Unexpected execution status: {status}')
  File "/home/travis/build/HumanCellAtlas/data-store/dss/util/__init__.py", line 91, in require
    reject(not condition, *args, exception=exception)
  File "/home/travis/build/HumanCellAtlas/data-store/dss/util/__init__.py", line 106, in reject
    raise exception(*args)
dss.util.RequirementError: Unexpected execution status: FAILED
----------------------------------------------------------------------
```

**Comment by Bento007** [comment] 2018-07-03 21:21
@xbrianh if you have any idea why this might have happened please add some details. Assign it back to me if you want me to try fixing it.

**Comment by hannes-ucsc** [comment] 2018-07-04 22:12
Since this is the storage verification test, I might be the first person to look at this,

**Comment by hannes-ucsc** [comment] 2018-07-04 22:56
Step 1812 in https://console.aws.amazon.com/states/home?region=us-east-1#/executions/details/arn:aws:states:us-east-1:861229788715:execution:dss-visitation-dev:IndexVisitation--c08ed3ce-dc65-4364-a80c-fe78c91ad494

Step 378 in https://console.aws.amazon.com/states/home?region=us-east-1#/executions/details/arn:aws:states:us-east-1:861229788715:execution:dss-visitation-dev:StorageVisitation--1ea38e22-f3c6-4a4f-a42c-860d016d87cd

Step  2111 in https://console.aws.amazon.com/states/home?region=us-east-1#/executions/details/arn:aws:states:us-east-1:861229788715:execution:dss-visitation-dev:StorageVisitation--385bbcb7-2a49-463e-9a23-a71236e61485

all have the same output:

{
  "error": "Lambda.SdkClientException",
  "cause": "Unable to execute HTTP request: The target server failed to respond"
}

Pretty sure this is a Lambda outage and nothing we can do about. Also note that three different visitations failed in the same run which hints at there having been a service outage, not a bug in the code.

**Comment by Bento007** [comment] 2018-07-09 18:47
Created a support ticket with AWS

**Comment by kozbo** [comment] 2018-07-09 18:49
Related to and possibly a dupe of #1401

**Closed** 2018-07-20 22:58 UTC
Labels: BUG, HIGH
