### ISSUE TITLE
Cannot unsubscribe from staging

### ISSUE THREAD

**Issue by jessebrennan** [HumanCellAtlas/data-store#2190] opened 2019-05-31 23:24 UTC
I'm trying to unsubscribe my personal Azul deployment from staging DSS and I'm getting a 500 error.

```
  File "/home/jesse/gi/azul/.venv/lib/python3.6/site-packages/hca/util/__init__.py", line 155, in __call__
    return self._consume_response(self._request(kwargs))
  File "/home/jesse/gi/azul/.venv/lib/python3.6/site-packages/hca/util/__init__.py", line 141, in _request
    timeout=self.client.timeout_policy)
  File "/home/jesse/gi/azul/.venv/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 425, in request
    headers=headers, data=data, **kwargs)
  File "/home/jesse/gi/azul/.venv/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jesse/gi/azul/.venv/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/jesse/gi/azul/.venv/lib/python3.6/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='dss.staging.data.humancellatlas.org', port=443): Max retries exceeded with url: /v1/subscriptions/26f7d855-dc14-4f22-82e7-8a3f0c2dd596?replica=aws&subscription_type=elasticsearch (Caused by ResponseError('too many 500 error responses',))
```

Digging into Kibana it seems like it corresponds to this internal error.

```
[ERROR]	2019-05-31T23:01:53.102Z	78c11db2-da49-45f1-8b5d-d1ebb15f0e77	Traceback (most recent call last):
  File "/var/task/chalicelib/dss/error.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/subscriptions.py", line 25, in delete
    return subscriptions_v1.delete(uuid, replica)
  File "/var/task/chalicelib/dss/util/security.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/var/task/chalicelib/dss/api/subscriptions_v1.py", line 169, in delete
    _unregister_percolate(es_client, doc_indexes, uuid)
  File "/var/task/chalicelib/dss/api/subscriptions_v1.py", line 186, in _unregister_percolate
    refresh=True)
  File "/var/task/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/task/elasticsearch/client/__init__.py", line 898, in delete_by_query
    doc_type, '_delete_by_query'), params=params, body=body)
  File "/var/task/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/var/task/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/var/task/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(413, '')
```

**Comment by hannes-ucsc** [comment] 2019-06-01 06:48
This is relatively urgent because it interferes with our ability to deploy Azul in our `dev` and `staging` deployments which both use DSS staging. Looking at @jessebrennan OP, this caused either by too many indices (in your ES domain, not Azul's) or too many subscriptions. If the latter, we may be partially to "blame" due to https://github.com/DataBiosphere/azul/issues/993. Before HMAC, we used to just skip making a subscription if no changes were necessary. Since we started using HMAC, that optimization is circumvented by the fact that we can't see whether the DSS has the right HMAC key because the `GET /subscriptions` response elides the HMAC key ID (for no good reason, IMO, since it is not secret). So we have to assume it doesn't and delete the existing subscription unconditionally and create a new one every time. That usage pattern should still be supported by the DSS which is why I put "blame" in quotes.

**Comment by hannes-ucsc** [comment] 2019-06-01 06:50
Personal and sandbox deployments of Azul are also affected.

**Comment by xbrianh** [comment] 2019-06-03 23:53
This behavior can only be reproduced on AWS Lambda, making debug efforts a little spicy. But a [fix has been proposed](https://github.com/HumanCellAtlas/data-store/pull/2196/files). Once it's merged into master, we'll cherry-pick the commit to staging, deploy, and ping this ticket.

**Comment by xbrianh** [comment] 2019-06-04 18:03
@jessebrennan @hannes-ucsc You should now be able to delete subscriptions in the staging deployment.

**Closed by xbrianh** 2019-06-04 18:03 UTC
