### ISSUE TITLE
SearchResult.results has no items, fails swagger validation

### ISSUE THREAD

**Issue by ttung** [HumanCellAtlas/data-store#1475] opened 2018-08-06 19:07 UTC
```
  SearchResult:
    type: object
    properties:
      es_query:
	description: Elasticsearch query used to produce the results.
        type: object
      results:
        description: Results matching the `es_query`.
        type: array
      total_hits:
        description: The total number of matching results found.
        type: integer
```

items of type array should have an items key describing what sort of items are returned.

https://swagger.io/docs/specification/data-models/data-types/#array

`Unlike JSON Schema, the items keyword is required in arrays.`

**Comment by mweiden** [comment] 2018-08-20 20:18
This is a duplicate of https://github.com/HumanCellAtlas/data-store/issues/1202. Closing this.

**Closed by mweiden** 2018-08-20 20:18 UTC
Labels: BUG
