### ISSUE TITLE
Checkout service should answer requests synchronously if possible

### ISSUE THREAD

**Issue by ttung** [HumanCellAtlas/data-store#1498] opened 2018-08-13 22:05 UTC
GET /bundle/ and GET /files/ can probably answer requests synchronously if it can verify that the checkout is already present, and meets the advertised TTL.

**Comment by mweiden** [comment] 2018-08-20 20:07
This is a duplicate of https://github.com/HumanCellAtlas/data-store/issues/1347. Closing this.

**Closed by mweiden** 2018-08-20 20:07 UTC
