### ISSUE TITLE
List collections

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/data-store#1729] opened 2018-11-16 18:25 UTC
## User story
* As a user
* I want to find collections I own and public collections
* so that keep track of collections.

## Definition of done
* Users can list public collections
* Users can list all view able collections
* Users can list all collection they own

**Comment by kozbo** [comment] 2019-03-15 02:04
dupe of #1932 closing

**Closed by kozbo** 2019-03-15 02:04 UTC
Labels: collections
