### ISSUE TITLE
Cleanup after bundle structure support is implemented

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-store#1479] opened 2018-08-06 20:24 UTC
# Definition of done

Complete the following steps for `dev`, `integration`, and `staging`. For `prod`, coordinate this with Ingest team.

1. clean out the old buckets
2. delete old indices from elasticsearch
3. reindex

- [x] `dev`
- [ ] `integration`
- [ ] `staging`

**Comment by hannes-ucsc** [comment] 2018-08-06 20:39
Hi @daniwelter, are you still the point person for planning the re-ingestion of the preview bundles using the new restructured bundle format? Blue is getting closer to supporting the new format and will be rolling out those changes to `dev`, `integration` and `staging`. 

Blue removed support for the old bundle format and plans on starting with a clean slate in each environment, completely deleting all existing bundles in those environments.  This is what this ticket is about. 

But before we promote Blue's changes to `prod` and create the clean slate there, the reingestion of the preview bundles needs to be ready to go.

In fact, I would propose that we test the preview bundle reingestion in `integration` first, then `staging` and then `prod`.

**Comment by hannes-ucsc** [comment] 2018-08-09 18:04
Great, thank you, @daniwelter. @xbrianh or I will ping you here once we cleaned out integration so we can start testing the reingestion.

**Comment by daniwelter** [comment] 2018-08-20 19:37
@hannes-ucsc any update on when you might be ready to test reingesting preview data?

**Comment by Bento007** [comment] 2018-09-17 20:18
is a duplicate of #1578

**Closed by Bento007** 2018-09-17 20:18 UTC
